create table
  public.users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'pdt'::text),
    email text not null,
    username text not null,
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email),
    constraint users_username_key unique (username)
  ) tablespace pg_default;

create table
  public.user_balances (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'pdt'::text),
    user_id bigint not null,
    balance_change bigint not null default '0'::bigint,
    constraint user_balances_pkey primary key (id),
    constraint user_balances_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;