-- WARNING: THIS SCRIPT WILL **NUKE** THE DATABASE YOU RUN IT ON AND REPLACE IT WITH THE DOGGY TABLES
-- NOTE: Some minor insignificant changes have been made to the schema to make it easier to work with locally
--  1. uniqueness constraint removed from bet_placement_id in bets table to make generating load data less of a pain
--  2. auth.users was removed and any foreign key dependencies on auth.users (uuid) were switched to profiles (user_id)

DO $$ 
DECLARE
    r RECORD;
BEGIN
    -- Select all tables from the information schema, and loop through them
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP;
END $$;

create table
  public.profiles (
    user_id uuid not null default extensions.uuid_generate_v4 (),
    username text null,
    constraint profiles_pkey primary key (user_id)
) tablespace pg_default;

create table
  public.games (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'pdt'::text),
    constraint games_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.entrants (
    id bigint generated by default as identity not null,
    game_id bigint not null,
    created_at timestamp with time zone not null default (now() at time zone 'pdt'::text),
    name text null,
    weapon text null,
    owner_id uuid null,
    constraint entrants_pkey primary key (id),
    constraint entrants_game_id_fkey foreign key (game_id) references games (id) on delete cascade,
    constraint entrants_owner_id_fkey foreign key (owner_id) references profiles (user_id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.completed_games (
    game_id bigint generated by default as identity not null,
    completed_at timestamp with time zone not null default (now() at time zone 'pdt'::text),
    constraint completed_games_pkey primary key (game_id),
    constraint completed_games_game_id_fkey foreign key (game_id) references games (id) on delete cascade
  ) tablespace pg_default;

create table
  public.players (
    id uuid not null,
    game_id bigint null,
    constraint players_game_id_fkey foreign key (game_id) references games (id),
    constraint players_id_fkey foreign key (id) references profiles (user_id)
  ) tablespace pg_default;

create table
  public.rounds (
    id bigint generated by default as identity not null,
    game_id bigint null,
    prev_round_id bigint null,
    constraint rounds_pkey primary key (id),
    constraint rounds_prev_round_id_key unique (prev_round_id),
    constraint rounds_game_id_fkey foreign key (game_id) references games (id) on delete cascade,
    constraint rounds_prev_round_id_fkey foreign key (prev_round_id) references rounds (id)
  ) tablespace pg_default;

create table
  public.matches (
    id bigint generated by default as identity not null,
    round_id bigint null,
    entrant_one bigint null,
    entrant_two bigint null,
    created_at timestamp with time zone not null default (now() at time zone 'pdt'::text),
    constraint matches_pkey primary key (id),
    constraint matches_entrant_one_fkey foreign key (entrant_one) references entrants (id) on delete cascade,
    constraint matches_entrant_two_fkey foreign key (entrant_two) references entrants (id) on delete cascade,
    constraint matches_round_id_fkey foreign key (round_id) references rounds (id) on delete cascade
  ) tablespace pg_default;

create table
  public.match_stories (
    match_id bigint generated by default as identity not null,
    story text null,
    constraint match_stories_pkey primary key (match_id),
    constraint match_stories_match_id_fkey foreign key (match_id) references matches (id)
  ) tablespace pg_default;;

create table
  public.user_balances (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default (now() at time zone 'pdt'::text),
    balance_change bigint not null default '0'::bigint,
    user_id uuid null,
    match_id bigint null,
    game_id bigint not null,
    constraint user_balances_pkey primary key (id),
    constraint user_balances_match_id_fkey foreign key (match_id) references matches (id),
    constraint user_balances_user_id_fkey foreign key (user_id) references profiles (user_id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.completed_matches (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    constraint completed_matches_pkey primary key (id),
    constraint completed_matches_id_fkey foreign key (id) references matches (id)
  ) tablespace pg_default;

-- REMOVED UNIQUENESS CONSTRAINT ON BET_PLACEMENT_ID. Makes generating load easier
create table
  public.bets (
    id bigint generated by default as identity not null,
    user_id uuid null default gen_random_uuid (),
    entrant_id bigint null,
    match_id bigint null,
    amount bigint not null default '0'::bigint,
    bet_placement_id bigint not null,
    constraint bets_pkey primary key (id),
    constraint bets_entrant_id_fkey foreign key (entrant_id) references entrants (id) on delete cascade,
    constraint bets_match_id_fkey foreign key (match_id) references matches (id) on delete cascade,
    constraint bets_user_id_fkey foreign key (user_id) references profiles (user_id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.completed_rounds (
    round_id bigint generated by default as identity not null,
    completed_at timestamp with time zone not null default (now() at time zone 'pdt'::text),
    constraint completed_rounds_pkey primary key (round_id),
    constraint completed_rounds_round_id_fkey foreign key (round_id) references rounds (id) on delete cascade
  ) tablespace pg_default;

create table
  public.match_victors (
    id bigint generated by default as identity not null,
    match_id bigint null,
    entrant_id bigint null,
    constraint match_victors_pkey primary key (id),
    constraint match_victors_entrant_id_fkey foreign key (entrant_id) references entrants (id) on delete cascade,
    constraint match_victors_match_id_fkey foreign key (match_id) references matches (id) on delete cascade
  ) tablespace pg_default;

create table
  public.match_losers (
    id bigint generated by default as identity not null,
    match_id bigint null,
    entrant_id bigint null,
    constraint match_losers_pkey primary key (id),
    constraint match_losers_entrant_id_fkey foreign key (entrant_id) references entrants (id) on delete cascade,
    constraint match_losers_match_id_fkey foreign key (match_id) references matches (id) on delete cascade
  ) tablespace pg_default;


